[workspace]
members = [
    "app",
    "app-web",
    "pob",
    "poe-tree",
    "shared",
    "worker"
]
exclude = ["snapshot"]

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
