[build]
target = "app-web/index.html"
dist = "app-web/dist"

[clean]
dist = "app-web/dist"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "yarn tailwindcss -i app-web/tailwind.css -o $TRUNK_STAGING_DIR/styles.css --minify"]
