name = "ssr-workers"
type = "javascript"
workers_dev = true
compatibility_date = "2023-03-23"

[[kv_namespaces]]
binding = "B2_CREDENTIALS"
id = "<unset>"

[[r2_buckets]]
binding = 'STORAGE_BUCKET'
bucket_name = 'r2storage'

[build]
command = "./build.sh --dev"

[build.upload]
dir    = "worker/build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["worker/**/*.wasm"]
type  = "CompiledWasm"

[site]
bucket = "./app/dist"
exclude = ["./app/dist/.stage"]

[miniflare]
cache = false
kv_persist = true
r2_persist = true
