name = "ssr-workers"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-05"

[[kv_namespaces]]
binding = "B2_CREDENTIALS"
id = "<unset>"

[[kv_namespaces]]
binding = "PASTE_STORAGE"
id = "<unset>"

[build]
command = "./build.sh --dev"

[build.upload]
dir    = "worker/build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["worker/**/*.wasm"]
type  = "CompiledWasm"

[site]
bucket = "./app-web/dist"
exclude = ["./app-web/dist/.stage"]

[miniflare]
cache = false
kv_persist = true
