name = "pasteofexile"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-05"

[build]
command = "./build.sh --release"

[build.upload]
dir    = "worker/build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

[site]
bucket = "./app/dist"
exclude = ["./app/dist/.stage"]
