[package]
name = "snapshot"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[dependencies]
pob = { path = "../pob/" }
clap = { version = "3.2", features = ["derive"] }
serde = "1"
csv = "1"
zip = "0.6"
anyhow = "1"

