[package]
name = "app"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[features]
default = ["client"]
ssr = ["sycamore/ssr", "strum"]
client = [
    "sycamore/experimental-hydrate",
    "wasm-bindgen-futures",
    "gloo-timers",
    "console_error_panic_hook",
    "tracing-subscriber",
    "tracing-wasm"
]

[dependencies]
pob = { path = "../pob/" }
shared = { path = "../shared/" }

# sycamore = { version = "0.7", features = ["futures"] }
# sycamore-router = "0.7"
# sycamore = { path = "../../sycamore/packages/sycamore", features = ["futures"] }
# sycamore-router = { path = "../../sycamore/packages/sycamore-router" }
sycamore = { git = "https://github.com/sycamore-rs/sycamore.git", rev = "f1fd670", package = "sycamore", features = ["futures"] }
sycamore-router = { git = "https://github.com/sycamore-rs/sycamore.git", rev = "f1fd670", package = "sycamore-router" }

# TODO: lot's of this stuff is only required in the client feature
web-sys = { version = "0.3", features = [
    "Window", "HtmlDocument", "HtmlHeadElement", "HtmlTextAreaElement", "Selection",
    "CssStyleDeclaration", "PointerEvent", "HtmlSelectElement", "InputEvent"
]}
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = { version = "0.4", optional = true }
reqwasm = "0.4" # TODO: this should be optional

serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.13"

console_error_panic_hook = { version = "0.1", optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", optional = true }
tracing-wasm = { version = "0.2", optional = true }

cfg-if = "1"
lazycell = "1"
anyhow = "1"
thiserror = "1"
strum = { version = "0.24", features = ["derive"], optional = true }

gloo-timers = { version = "0.2", features = ["futures"], optional = true }
thousands = "0.2"
itertools = "0.10"


[dev-dependencies]
sycamore = { git = "https://github.com/sycamore-rs/sycamore.git", rev = "f1fd670", package = "sycamore", features = ["ssr"] }
