[package]
name = "app"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[features]
default = ["client"]
ssr = ["sycamore/ssr"]
client = ["sycamore/experimental-hydrate", "web-sys", "reqwasm", "wasm-bindgen-futures"]

[dependencies]
sycamore = "0.7"
sycamore-router = "0.7"
# sycamore = { path = "../../sycamore/packages/sycamore" }
# sycamore-router = { path = "../../sycamore/packages/sycamore-router" }
web-sys = { version = "0.3", optional = true }
wasm-bindgen-futures = { version = "0.4.28", optional = true }
reqwasm = { version = "0.4", optional = true }
console_error_panic_hook = "0.1"
console_log = "0.2"
log = "0.4"
cfg-if = "1"
pob = { path = "../pob/" }
lazycell = "1"
anyhow = "1"
