[package]
name = "shared"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
percent-encoding.workspace = true
thiserror.workspace = true
