[package]
name = "worker"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
debug = ["console_log", "console_error_panic_hook", "fern"]

[dependencies]
app = { path = "../app", features = ["ssr"], default-features = false }
cfg-if = "0.1.2"
worker = { git = "https://github.com/Dav1dde/workers-rs.git", rev = "75681ad", package = "worker" }
# worker = { path = "../../workers-rs/worker/" }
serde_json = "1"
serde = "1"
web-sys = { version = "0.3", features = ["Crypto", "SubtleCrypto", "WorkerGlobalScope"] }
wasm-bindgen = "0.2.78"
js-sys = "0.3.55"
base64 = "0.13"
pob = { path = "../pob/" }
thiserror = "1"
log = "0.4"
fern = { version = "0.6", optional = true }
console_log = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1.1", optional = true }
