[package]
name = "worker-app" # Can't use worker because it collides with worker-rs
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
debug = ["console_log", "console_error_panic_hook", "fern"]
use-kv-storage = []

[dependencies]
app = { path = "../app", features = ["ssr"], default-features = false }
pob = { path = "../pob/" }

worker = { git = "https://github.com/Dav1dde/workers-rs.git", rev = "5a24cc5d", package = "worker" }
# worker = { path = "../../workers-rs/worker/" }

serde_json = "1"
serde = "1"

web-sys = { version = "0.3", features = ["Crypto", "SubtleCrypto", "WorkerGlobalScope"] }
wasm-bindgen = "0.2"
js-sys = "0.3"

base64 = "0.13"
thiserror = "1"
git-version = "0.3"

log = "0.4"
fern = { version = "0.6", optional = true }
console_log = { version = "0.2", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
