[package]
name = "worker"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
app = { path = "../app", features = ["ssr"], default-features = false }
cfg-if = "0.1.2"
# worker = { git = "https://github.com/cloudflare/workers-rs", rev = "8a044327", package = "worker" }
worker = { git = "https://github.com/Dav1dde/workers-rs.git", rev = "12ff82f", package = "worker" }
# worker = { path = "../../workers-rs/worker" }
serde_json = "1.0.67"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }
