[package]
name = "pob"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[dependencies]
flate2 = "1"
log = "0.4"
base64 = "0.13"
serde = { version = "1", features = [ "derive" ] }
serde_with = "1"
quick-xml = { version = "0.22", features = [ "serialize" ] }
roxmltree = { version = "0.14" }
anyhow = "1"
thiserror = "1"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parse"
harness = false

