[package]
name = "pob"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[dependencies]
flate2 = "1"
log = "0.4"
base64 = "0.13"
serde = { version = "1", features = [ "derive" ] }
serde_with = "1"
quick-xml = { version = "0.23.0-alpha3", features = [ "serialize" ] }
# quick-xml = { git = "https://github.com/tafia/quick-xml.git", rev = "d872771", features = [ "serialize" ] }
# quick-xml = { path = "../../quick-xml/", features = ["serialize"] }
anyhow = "1"
thiserror = "1"
owning_ref = "0.4"
